### PR TITLE
make last changes a public property

### PR DESCRIPTION
**Pull request by redbrain**
addresses #37

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @redbrain,

With this change you were able to access lastChanges variable in a pipeline script?

If so, can you try adding a 'transient' keyword to the LastChanges variable?

This instructs Jenkins to not save it into disk (serialize), as this variable can contain lots of data it might not be a good idea to serialize it.

**Comment by redbrain** [comment]
No this isn't a full fix will close the pull request i need to follow how artifactory DSL does this:

https://github.com/JFrogDev/jenkins-artifactory-plugin/blob/master/src/main/java/org/jfrog/hudson/pipeline/dsl/ArtifactoryPipelineGlobal.java

Should give LastChanges object that we can call .getLastChanges  from.

**Comment by rmpestano** [comment]
No Problem, you can leave the PR open and when you find the solution just commit and it will be append to this PR.

I've looked into the Artifactory plugin and have no idea on what they are doing ;). But don't give up, your idea is nice!

**Comment by redbrain** [comment]
Hey starting to get somewhere with this now the last commit allows for:

```
def publisher = LastChanges.publisher "LAST_SUCCESSFUL_BUILD", "SIDE", "LINE", true, true, "", "", "", "code/dbx2LseMillennium", ""
        publisher.publish ()
        def changes = publisher.getLastChanges ()
        println (changes)
```

**Comment by redbrain** [comment]
Got this far now:

`    stage("last-changes") {
        def publisher = LastChanges.publisher "LAST_SUCCESSFUL_BUILD", "SIDE", "LINE", true, true, "", "", "", "code/dbx2LseMillennium", ""
        publisher.publish ()
        def changes = publisher.getLastChanges ()
        changes.getCommits ().each {
            println "change ${it}"
        }
    }`

**Comment by redbrain** [comment]
Got this working for me now what do you think of this pipeline:

```
stage("last-changes") {
        def publisher = LastChanges.publisher "LAST_SUCCESSFUL_BUILD", "SIDE", "LINE", true, true, "", "", "", "code/dbx2LseMillennium", ""
        publisher.publish ()
        def changes = publisher.getLastChanges ()
        for (commit in changes.getCommits ()) {
            println(commit)
            def commitInfo = commit.getCommitInfo ()
            println(commitInfo)
            println(commitInfo.getCommitMessage ())
        }
    }
```

**Comment by rmpestano** [comment]
Hi @redbrain,

```
Publishing build last changes...
Last changes from revision bf640e5 to 1f222cd published successfully!
[Pipeline] publish
[Pipeline] echo
com.github.jenkins.lastchanges.model.CommitChanges@52500e87
[Pipeline] echo
Commit: bf640e5b348cb68b8b6221c714fa7cb731913f31
Author: GitHub
E-mail: noreply@github.com
Date: 04/01/2018 08:38:22 GMT-02:00
Message: Merge pull request #39 from jsoref/spelling

Spelling


[Pipeline] echo
Merge pull request #39 from jsoref/spelling

Spelling
```

This is wonderful, the code also looks great! Thank you very much for your contribution!

I'll do some tests and then release a new version soon

Thank you very much.

**Comment by redbrain** [comment]
Thanks for this epic plugin! 💃

**Comment by rmpestano** [comment]
Hi again @redbrain,

I think [PublishLastChangesStep](https://github.com/redbrain/last-changes-plugin/blob/master/src/main/java/com/github/jenkins/lastchanges/pipeline/PublishLastChangesStep.java) isn't being used, I think [GetLastChangesPublisherStep](https://github.com/redbrain/last-changes-plugin/blob/master/src/main/java/com/github/jenkins/lastchanges/pipeline/GetLastChangesPublisherStep.java) is the one being used. Can you remove the unused one?  

Also can you rename it to  PublishLastChangesStep? [and here in](https://github.com/redbrain/last-changes-plugin/blob/965c3ef66dc54b09bbd85ad44af2394e1ccc43eb/src/main/java/com/github/jenkins/lastchanges/pipeline/GetLastChangesPublisherStep.java#L82) function name I'd prefer "publishLastChanges" because "getPublisher" is too generic, what do you think?

I also would like to rename the [pipeline/LastChangesPublisher](https://github.com/redbrain/last-changes-plugin/blob/master/src/main/java/com/github/jenkins/lastchanges/pipeline/LastChangesPublisher.java)  to avoid confusion with [current publish](https://github.com/redbrain/last-changes-plugin/blob/master/src/main/java/com/github/jenkins/lastchanges/LastChangesPublisher.java), something like PipelineLastChangesPublisher or LastChangesPublisherScript.

Can you make those changes? thank you again.

**Comment by rmpestano** [comment]
I think now I got it, there are two steps, one to get the publisher (getPublisher) and another invoke it (publish).

Taking that into account I think we can just rename `getPublisher` to `getLastChangesPublisher`, and rename the function [publish](https://github.com/redbrain/last-changes-plugin/blob/965c3ef66dc54b09bbd85ad44af2394e1ccc43eb/src/main/java/com/github/jenkins/lastchanges/pipeline/PublishLastChangesStep.java#L57) to `publishLastChanges`, what do you think?

**Comment by redbrain** [comment]
Updated against your review pipeline looks like this now:

```
stage("last-changes") {
        def publisher = LastChanges.getLastChangesPublisher "LAST_SUCCESSFUL_BUILD", "SIDE", "LINE", true, true, "", "", "", "code", ""
        publisher.publishLastChanges ()
        def changes = publisher.getLastChanges ()
        for (commit in changes.getCommits ()) {
            println(commit)
            def commitInfo = commit.getCommitInfo ()
            println(commitInfo)
            println(commitInfo.getCommitMessage ())
        }
    }
```

**Pull request merged**
